name: Readme Updater

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [ main ]
    paths:
    - '**/README.md'

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: actions-cicd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidfort/k8s-scanner
          readme-filepath: ./README.md
          short-description: RapidFort Kubernetes SCA scanner
